---
abstract: 'Chained actions for Dancer'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  Dancer::Test: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer-Plugin-Chain
provides:
  Dancer::Plugin::Chain:
    file: lib/Dancer/Plugin/Chain.pm
    version: v0.1.1
requires:
  Dancer: '0'
  Dancer::Plugin: '0'
  List::Util: '0'
  Moose: '0'
  Ref::Util: '0'
  overload: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Dancer-Plugin-Chain/issues
  homepage: https://github.com/yanick/Dancer-Plugin-Chain
  repository: https://github.com/yanick/Dancer-Plugin-Chain.git
version: 0.1.1
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_serialization_backend: 'YAML::Tiny version 1.67'
