---
abstract: 'Chained actions for Dancer'
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  Dancer::Test: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.3601
  Test::More: 0.88
  perl: 5.006
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Chain
provides:
  Dancer::Plugin::Chain:
    file: lib/Dancer/Plugin/Chain.pm
    version: v0.1.0
requires:
  Dancer: 0
  Dancer::Plugin: 0
  Moose: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dancer-Plugin-Chain
  homepage: http://search.cpan.org/dist/Dancer-Plugin-Chain/
  repository: https://github.com/yanick/Dancer-Plugin-Chain.git
version: 0.1.0
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributors:
  - 'Yanick Champoux <yanick@cpan.org>'
